### PR TITLE
Add output_file variable when using layouts

### PR DESCRIPTION
**Pull request by gabrielpoca**
The `output_file` is relevant when there's a need to create a link to the current file from the layout.

### CODE REVIEW

**Comment by gabrielpoca** [comment]
@frm since you don't have a lot of time and this project doesn't have a lot of visibility, I think I'll just start merging these ok?

**Comment by frm** [comment]
Can you give me an example where this is needed?

**Comment by gabrielpoca** [comment]
Yap, for instance, you have a layout for every blog post and want to create a full link for people to copy

**Comment by gabrielpoca** [comment]
@frm bump

**Pull request merged**
